import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { LoadingState } from "../components/Feedback";
import { api, type AnalyticsThresholds } from "../services/api";

const defaultThresholds: AnalyticsThresholds = { attendanceLowPercent: 75, attendanceHighPercent: 90, performanceLowPercent: 40, performanceHighPercent: 80, lateCount: 5, consecutiveAbsences: 3 };
const timezoneExamples = ["America/Bogota", "America/Lima", "America/Mexico_City", "America/Santiago", "America/Argentina/Buenos_Aires", "America/New_York", "America/Los_Angeles", "Europe/Madrid", "Europe/London", "Asia/Tokyo", "UTC"];
export function SettingsPage() {
  const client = useQueryClient();
  const groups = useQuery({ queryKey: ["groups"], queryFn: api.getCourseGroups });
  const members = useQuery({ queryKey: ["memberships"], queryFn: api.getMemberships });
  const invites = useQuery({ queryKey: ["invitations"], queryFn: api.getInvitations });
  const thresholds = useQuery({ queryKey: ["analyticsThresholds"], queryFn: api.getAnalyticsThresholds });
  const institution = useQuery({ queryKey: ["institutionSettings"], queryFn: api.getInstitutionSettings });
  const [email, setEmail] = useState("");
  const [role, setRole] = useState<"ADMIN" | "DOCENTE">("DOCENTE");
  const [selectedGroups, setSelectedGroups] = useState<string[]>([]);
  const [notice, setNotice] = useState("");
  const [values, setValues] = useState<AnalyticsThresholds>(defaultThresholds);
  const [memberDrafts, setMemberDrafts] = useState<Record<string, { role: "ADMIN" | "DOCENTE"; courseGroupIds: string[] }>>({});
  const [institutionName, setInstitutionName] = useState("");
  const [timezone, setTimezone] = useState("America/Bogota");
  useEffect(() => { if (thresholds.data) setValues(thresholds.data.item); }, [thresholds.data]);
  useEffect(() => { if (institution.data) { setInstitutionName(institution.data.item.name); setTimezone(institution.data.item.timezone); } }, [institution.data]);

  const invite = useMutation({ mutationFn: api.createInvitation, onSuccess: async (result) => { setNotice(result.message); setEmail(""); setSelectedGroups([]); await Promise.all([client.invalidateQueries({ queryKey: ["invitations"] }), client.invalidateQueries({ queryKey: ["memberships"] })]); }, onError: (error) => setNotice(error instanceof Error ? error.message : "No fue posible crear la invitación.") });
  const revoke = useMutation({ mutationFn: api.revokeInvitation, onSuccess: async () => { setNotice("Invitación revocada."); await client.invalidateQueries({ queryKey: ["invitations"] }); }, onError: (error) => setNotice(error instanceof Error ? error.message : "No fue posible revocar la invitación.") });
  const saveThresholds = useMutation({ mutationFn: api.saveAnalyticsThresholds, onSuccess: async () => { setNotice("Umbrales guardados."); await client.invalidateQueries({ queryKey: ["analyticsThresholds"] }); await client.invalidateQueries({ queryKey: ["analytics"] }); }, onError: (error) => setNotice(error instanceof Error ? error.message : "No fue posible guardar los umbrales.") });
  const saveMember = useMutation({ mutationFn: ({ id, ...body }: { id: string; role: "ADMIN" | "DOCENTE"; courseGroupIds: string[] }) => api.updateMembership(id, body), onSuccess: async () => { setNotice("Membresía actualizada."); await client.invalidateQueries({ queryKey: ["memberships"] }); }, onError: (error) => setNotice(error instanceof Error ? error.message : "No fue posible actualizar la membresía.") });
  const removeMember = useMutation({ mutationFn: api.revokeMembership, onSuccess: async () => { setNotice("Acceso revocado y registrado en auditoría."); await Promise.all([client.invalidateQueries({ queryKey: ["memberships"] }), client.invalidateQueries({ queryKey: ["audit"] })]); }, onError: (error) => setNotice(error instanceof Error ? error.message : "No fue posible revocar la membresía.") });
  const saveInstitution = useMutation({ mutationFn: api.updateInstitutionSettings, onSuccess: async (result) => { setNotice("Configuración institucional guardada; los nuevos horarios usarán esta zona."); setInstitutionName(result.item.name); setTimezone(result.item.timezone); await Promise.all([client.invalidateQueries({ queryKey: ["institutionSettings"] }), client.invalidateQueries({ queryKey: ["attendanceContext"] })]); }, onError: (error) => setNotice(error instanceof Error ? error.message : "No fue posible actualizar la institución.") });
  const backup = useMutation({ mutationFn: api.downloadBackup, onSuccess: () => setNotice("Respaldo gzip privado descargado."), onError: (error) => setNotice(error instanceof Error ? error.message : "No se pudo descargar el respaldo.") });

  if (groups.isLoading || members.isLoading || invites.isLoading || thresholds.isLoading || institution.isLoading) return <LoadingState label="Cargando configuración institucional…" />;
  const error = groups.error ?? members.error ?? invites.error ?? thresholds.error ?? institution.error;
  if (error) return <section className="page"><p className="notice notice-error" role="alert">{error instanceof Error ? error.message : "No se pudo cargar la configuración."}</p></section>;
  return <section className="page">
    <div className="page-heading"><div><h1>Configuración</h1><p className="page-subtitle">Administra zona horaria, asignaciones de curso, invitaciones, alertas y exportación de respaldo privado.</p></div></div>
    {notice && <p className="notice notice-info" role="status">{notice}</p>}
    <article className="content-card"><h2>Institución y zona horaria</h2><p className="helper-text">Las reglas vigentes adoptarán la nueva zona horaria; las sesiones históricas conservan su instantánea original.</p><form className="form-grid compact-form" onSubmit={(event) => { event.preventDefault(); saveInstitution.mutate({ name: institutionName, timezone }); }}>
      <label className="form-field"><span>Nombre de la institución</span><input value={institutionName} onChange={(event) => setInstitutionName(event.target.value)} maxLength={120} required /></label>
      <label className="form-field"><span>Zona horaria IANA</span><input list="iana-timezones" value={timezone} onChange={(event) => setTimezone(event.target.value)} maxLength={64} required /><datalist id="iana-timezones">{timezoneExamples.map((zone) => <option value={zone} key={zone} />)}</datalist><small>Ejemplo: America/Bogota. El servidor valida que sea una zona IANA reconocida.</small></label>
      <div className="form-full"><button className="button button-primary" disabled={saveInstitution.isPending || !timezone.trim() || !institutionName.trim()}>{saveInstitution.isPending ? "Guardando…" : "Guardar institución"}</button></div>
    </form></article>

    <article className="content-card"><h2>Invitar docente o administrador</h2><p className="helper-text">SIRAE no envía correos. Comparte con la persona la dirección usada para registrarse o iniciar sesión. La invitación vence en 30 días y se consume tras el acceso de esa cuenta.</p><form className="form-grid compact-form" onSubmit={(event) => { event.preventDefault(); invite.mutate({ email, role, courseGroupIds: role === "DOCENTE" ? selectedGroups : [] }); }}>
      <label className="form-field"><span>Correo de la cuenta</span><input type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} required maxLength={254} /></label>
      <label className="form-field"><span>Rol</span><select value={role} onChange={(event) => setRole(event.target.value as typeof role)}><option value="DOCENTE">Docente</option><option value="ADMIN">Administrador</option></select></label>
      {role === "DOCENTE" && <fieldset className="form-field form-full"><legend>Cursos/grupos asignados</legend><div className="checkbox-list">{(groups.data?.items ?? []).map((group) => <label key={group.id}><input type="checkbox" checked={selectedGroups.includes(group.id)} onChange={(event) => setSelectedGroups(event.target.checked ? [...selectedGroups, group.id] : selectedGroups.filter((id) => id !== group.id))} />{group.label} · {group.academicYear}</label>)}</div></fieldset>}
      <div className="form-full"><button className="button button-primary" disabled={invite.isPending || !email.trim() || (role === "DOCENTE" && !selectedGroups.length)}>{invite.isPending ? "Creando…" : "Crear invitación"}</button></div>
    </form></article>

    <div className="feature-grid two-cols"><article className="content-card"><h2>Membresías activas</h2>{(members.data?.items ?? []).map((member) => {
      const draft = memberDrafts[member.id] ?? { role: member.role, courseGroupIds: member.courseGroupIds };
      return <div className="membership-row" key={member.id}><div className="membership-person"><strong>{member.name}</strong><small>{member.email ?? "Cuenta sin correo visible"}</small></div><div className="membership-controls"><label className="form-field"><span>Rol</span><select value={draft.role} onChange={(event) => setMemberDrafts((prior) => ({ ...prior, [member.id]: { ...draft, role: event.target.value as typeof draft.role } }))}><option value="ADMIN">Administrador</option><option value="DOCENTE">Docente</option></select></label><label className="form-field"><span>Cursos asignados</span><select multiple aria-label={`Cursos asignados a ${member.name}`} value={draft.courseGroupIds} onChange={(event) => setMemberDrafts((prior) => ({ ...prior, [member.id]: { ...draft, courseGroupIds: [...event.target.selectedOptions].map((option) => option.value) } }))}>{(groups.data?.items ?? []).map((group) => <option key={group.id} value={group.id}>{group.label}</option>)}</select></label><div className="membership-actions"><button className="button button-secondary compact-button" onClick={() => saveMember.mutate({ id: member.id, ...draft })} disabled={saveMember.isPending}>Guardar alcance</button><button className="button button-danger compact-button" onClick={() => { if (window.confirm(`¿Revocar el acceso de ${member.name}? Sus registros académicos se conservarán.`)) removeMember.mutate(member.id); }} disabled={removeMember.isPending}>Revocar acceso</button></div></div></div>;
    })}{!members.data?.items.length && <p className="helper-text">No hay membresías visibles.</p>}</article>
    <article className="content-card"><h2>Invitaciones pendientes</h2>{(invites.data?.items ?? []).length ? (invites.data?.items ?? []).map((invitation) => <div className="invite-row" key={invitation.id}><div><strong>{invitation.email}</strong><small>{invitation.role === "DOCENTE" ? "Docente" : "Administrador"} · vence {new Date(invitation.expiresAt).toLocaleDateString()}</small></div><button className="button button-secondary compact-button" onClick={() => revoke.mutate(invitation.id)} disabled={revoke.isPending}>Revocar</button></div>) : <p className="helper-text">No hay invitaciones pendientes.</p>}</article></div>

    <article className="content-card"><h2>Umbrales de alertas y patrones descriptivos</h2><p className="helper-text">Los umbrales ajustan las alertas, no las notas almacenadas. Para comparar periodos con escalas diferentes, el rendimiento se normaliza al rango configurado de cada uno.</p><form className="form-grid compact-form" onSubmit={(event) => { event.preventDefault(); saveThresholds.mutate(values); }}>
      <NumberField label="Asistencia baja (%)" value={values.attendanceLowPercent} min={0} max={100} onChange={(value) => setValues((prior) => ({ ...prior, attendanceLowPercent: value }))} /><NumberField label="Asistencia alta (%)" value={values.attendanceHighPercent} min={0} max={100} onChange={(value) => setValues((prior) => ({ ...prior, attendanceHighPercent: value }))} /><NumberField label="Rendimiento bajo normalizado (%)" value={values.performanceLowPercent} min={0} max={100} onChange={(value) => setValues((prior) => ({ ...prior, performanceLowPercent: value }))} /><NumberField label="Rendimiento alto normalizado (%)" value={values.performanceHighPercent} min={0} max={100} onChange={(value) => setValues((prior) => ({ ...prior, performanceHighPercent: value }))} /><NumberField label="Umbral de tardanzas" value={values.lateCount} min={1} max={100} onChange={(value) => setValues((prior) => ({ ...prior, lateCount: value }))} /><NumberField label="Ausencias consecutivas" value={values.consecutiveAbsences} min={1} max={30} onChange={(value) => setValues((prior) => ({ ...prior, consecutiveAbsences: value }))} />
      <div className="form-full"><button className="button button-primary" disabled={saveThresholds.isPending}>{saveThresholds.isPending ? "Guardando…" : "Guardar umbrales"}</button></div></form></article>
    <article className="content-card backup-card"><div><h2>Respaldo de datos</h2><p className="helper-text">Exporta un archivo gzip privado de la institución y adjuntos GridFS. Contiene datos personales y debe guardarse con acceso restringido. La restauración controlada se documenta en el repositorio.</p></div><button className="button button-secondary" onClick={() => backup.mutate()} disabled={backup.isPending}>{backup.isPending ? "Preparando…" : "Descargar respaldo"}</button></article>
  </section>;
}
function NumberField({ label, value, min, max, onChange }: { label: string; value: number; min: number; max: number; onChange: (value: number) => void }) { return <label className="form-field"><span>{label}</span><input type="number" min={min} max={max} value={value} onChange={(event) => onChange(Number(event.target.value))} /></label>; }
