import type { NextFunction, Request, Response } from "express";
import { z } from "zod";
import mongoose from "mongoose";
import { createHash } from "node:crypto";
import { GridFSBucket, type ObjectId } from "mongodb";
import ExcelJS from "exceljs";
import type { AuthContext } from "../services/auth-context.js";
import { requireAuthContext } from "../middleware/security.js";
import { createSessionInput, subjectInput, periodInput, categoryInput, assessmentInput, gradeInput, scheduleInput, scheduleUpdateInput, scanInput, manualAttendanceInput, observationInput, assessmentUpdateInput, gradingModeInput, scheduleBreakInput, sessionAdjustInput, attendanceLinkInput } from "../validators/learning.js";
import { createCategory, createAssessment, deleteAssessment, setGradingMode, updateAssessment, createPeriod, createSubject, listGradeSetup, listPeriods, listSubjects, listGrades, upsertGrade } from "../services/grades.js";
import { closeClassSession, listSessionAttendance, scanQr, setManualAttendance } from "../services/attendance.js";
import { adjustClassSession, createSchedule, createScheduleBreak, deleteScheduleBreak, listScheduleBreaks, deactivateSchedule, ensureClassSession, getSessionContext, listSchedules, listSessions, updateSchedule } from "../services/schedules.js";
import { createObservation, listObservations } from "../services/observations.js";
import { closeAttendanceLink, getAttendanceLink, openAttendanceLink } from "../services/attendance-link.js";
import { confirmImport, previewImport, remapImport, type ImportUpload } from "../services/imports.js";
import { analyticsThresholds, getAnalytics, updateAnalyticsThresholds } from "../services/analytics.js";
import { AuditLog, CourseGroup, Institution, Membership, MembershipInvitation, Student, User } from "../models/index.js";
import { Observation, Schedule } from "../models/learning.js";
import { AppError } from "../utils/errors.js";
import { actorId, tenantId, objectId, assertGroupAccess, audit } from "../services/learning-common.js";

const admin = (context: AuthContext) => { if (context.membership.role !== "ADMIN") throw new AppError(403, "FORBIDDEN", "Esta acción requiere el rol administrador."); };
const run = (handler: (req: Request, res: Response, auth: AuthContext) => Promise<void>) => async (req: Request, res: Response, next: NextFunction) => { try { await handler(req, res, requireAuthContext(req)); } catch (error) { next(error); } };
const idSchema = z.object({ id: z.string().regex(/^[a-f\d]{24}$/i) });
type UploadedRequest = Request & { file?: ImportUpload };
export const subjectList = run(async (_req, res, auth) => { res.json({ items: await listSubjects(auth) }); });
export const importTemplateDownload = run(async (req, res, _auth) => {
  const kind = "students";
  const format = req.query.format === "xlsx" ? "xlsx" : "csv";
  const headers = ["nombre", "apellido", "curso", "grupo", "asignatura"];
  const filename = `plantilla-${kind}.${format}`;
  if (format === "csv") {
    res.setHeader("Content-Type", "text/csv; charset=utf-8");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    res.send(`\uFEFF${headers.join(",")}\r\n`);
    return;
  }
  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet("Estudiantes");
  sheet.addRow(headers);
  sheet.getRow(1).font = { bold: true };
  sheet.views = [{ state: "frozen", ySplit: 1 }];
  sheet.columns = headers.map((header) => ({ header, key: header, width: Math.max(14, header.length + 4) }));
  const buffer = await workbook.xlsx.writeBuffer();
  res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
  res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
  res.send(Buffer.from(buffer));
});
export const subjectCreate = run(async (req, res, auth) => { admin(auth); res.status(201).json({ item: await createSubject(auth, subjectInput.parse(req.body)) }); });
export const periodList = run(async (_req, res, auth) => { res.json({ items: await listPeriods(auth) }); });
export const periodCreate = run(async (req, res, auth) => { admin(auth); res.status(201).json({ item: await createPeriod(auth, periodInput.parse(req.body)) }); });
export const gradeSetup = run(async (req, res, auth) => { res.json(await listGradeSetup(auth, typeof req.query.periodId === "string" ? req.query.periodId : undefined, typeof req.query.subjectId === "string" ? req.query.subjectId : undefined)); });
export const categoryCreate = run(async (req, res, auth) => { res.status(201).json({ item: await createCategory(auth, categoryInput.parse(req.body)) }); });
export const assessmentCreate = run(async (req, res, auth) => { res.status(201).json({ item: await createAssessment(auth, assessmentInput.parse(req.body)) }); });
export const gradeList = run(async (req, res, auth) => { res.json({ items: await listGrades(auth, { periodId: typeof req.query.periodId === "string" ? req.query.periodId : undefined, subjectId: typeof req.query.subjectId === "string" ? req.query.subjectId : undefined, studentId: typeof req.query.studentId === "string" ? req.query.studentId : undefined }) }); });
export const gradeSave = run(async (req, res, auth) => { res.json({ item: await upsertGrade(auth, gradeInput.parse(req.body)) }); });
export const scheduleList = run(async (_req, res, auth) => { res.json({ items: await listSchedules(auth) }); });
export const assessmentUpdate = run(async (req, res, auth) => { const { id } = idSchema.parse(req.params); res.json({ item: await updateAssessment(auth, id, assessmentUpdateInput.parse(req.body)) }); });
export const assessmentDelete = run(async (req, res, auth) => { const { id } = idSchema.parse(req.params); res.json({ item: await deleteAssessment(auth, id) }); });
export const gradingModeSave = run(async (req, res, auth) => { res.json({ item: await setGradingMode(auth, gradingModeInput.parse(req.body)) }); });
export const scheduleBreakList = run(async (_req, res, auth) => { res.json({ items: await listScheduleBreaks(auth) }); });
export const scheduleBreakCreate = run(async (req, res, auth) => { res.status(201).json({ item: await createScheduleBreak(auth, scheduleBreakInput.parse(req.body)) }); });
export const scheduleBreakDelete = run(async (req, res, auth) => { const { id } = idSchema.parse(req.params); res.json({ item: await deleteScheduleBreak(auth, id) }); });
export const scheduleCreate = run(async (req, res, auth) => { res.status(201).json({ item: await createSchedule(auth, scheduleInput.parse(req.body)) }); });
export const scheduleUpdate = run(async (req, res, auth) => { const { id } = idSchema.parse(req.params); res.json({ item: await updateSchedule(auth, id, scheduleUpdateInput.parse(req.body)) }); });
export const scheduleDeactivate = run(async (req, res, auth) => { const { id } = idSchema.parse(req.params); res.json({ item: await deactivateSchedule(auth, id) }); });
export const institutionSettingsGet = run(async (_req, res, auth) => { const institution = await Institution.findOne({ _id: tenantId(auth), active: true }).lean(); if (!institution) throw new AppError(404, "INSTITUTION_NOT_FOUND", "No se encontró la institución."); res.json({ item: { id: String(institution._id), name: institution.name, timezone: institution.timezone } }); });
export const institutionSettingsPut = run(async (req, res, auth) => {
  admin(auth);
  const body = z.object({ name: z.string().trim().min(2).max(120).optional(), timezone: z.string().trim().min(1).max(64).optional() }).refine((value) => Object.keys(value).length > 0, "Incluye al menos un campo para actualizar.").parse(req.body);
  if (body.timezone) { try { new Intl.DateTimeFormat("en-US", { timeZone: body.timezone }).format(new Date()); } catch { throw new AppError(400, "TIMEZONE_INVALID", "Escribe una zona horaria IANA válida, por ejemplo America/Bogota o Europe/Madrid."); } }
  const institution = await Institution.findOne({ _id: tenantId(auth), active: true });
  if (!institution) throw new AppError(404, "INSTITUTION_NOT_FOUND", "No se encontró la institución.");
  const before = { name: institution.name, timezone: institution.timezone };
  if (body.name !== undefined) institution.name = body.name;
  if (body.timezone !== undefined) institution.timezone = body.timezone;
  await institution.save();
  if (body.timezone && body.timezone !== before.timezone) await Schedule.updateMany({ institutionId: tenantId(auth), active: true }, { $set: { timezone: body.timezone } });
  await audit(auth, "INSTITUTION_SETTINGS_UPDATED", "Institution", tenantId(auth), before, { name: institution.name, timezone: institution.timezone });
  res.json({ item: { id: String(institution._id), name: institution.name, timezone: institution.timezone } });
});
export const sessionContext = run(async (_req, res, auth) => { res.json(await getSessionContext(auth)); });
export const sessionList = run(async (req, res, auth) => { res.json({ items: await listSessions(auth, typeof req.query.date === "string" ? req.query.date : undefined) }); });
export const attendanceLinkGet = run(async (req, res, auth) => { const { id } = idSchema.parse({ id: req.params.sessionId }); res.json({ item: await getAttendanceLink(auth, id) }); });
export const attendanceLinkOpen = run(async (req, res, auth) => { const { id } = idSchema.parse({ id: req.params.sessionId }); res.json({ item: await openAttendanceLink(auth, id, attendanceLinkInput.parse(req.body)) }); });
export const attendanceLinkClose = run(async (req, res, auth) => { const { id } = idSchema.parse({ id: req.params.sessionId }); res.json({ item: await closeAttendanceLink(auth, id) }); });
export const sessionAdjust = run(async (req, res, auth) => { const { id } = idSchema.parse({ id: req.params.sessionId }); res.json({ item: await adjustClassSession(auth, id, sessionAdjustInput.parse(req.body)) }); });
export const sessionEnsure = run(async (req, res, auth) => { res.status(201).json({ item: await ensureClassSession(auth, createSessionInput.parse(req.body)) }); });
export const attendanceScan = run(async (req, res, auth) => { const { sessionId } = z.object({ sessionId: idSchema.shape.id }).parse(req.params); res.json(await scanQr(auth, scanInput.parse({ ...req.body, classSessionId: sessionId }))); });
export const attendanceRoster = run(async (req, res, auth) => { const { sessionId } = z.object({ sessionId: idSchema.shape.id }).parse(req.params); res.json(await listSessionAttendance(auth, sessionId)); });
export const attendanceMark = run(async (req, res, auth) => { const { sessionId } = z.object({ sessionId: idSchema.shape.id }).parse(req.params); res.json({ item: await setManualAttendance(auth, sessionId, manualAttendanceInput.parse(req.body)) }); });
export const attendanceClose = run(async (req, res, auth) => { const { sessionId } = z.object({ sessionId: idSchema.shape.id }).parse(req.params); res.json({ item: await closeClassSession(auth, sessionId) }); });
export const observationList = run(async (req, res, auth) => { const studentId = typeof req.query.studentId === "string" ? req.query.studentId : undefined; if (studentId) { const student = await Student.findOne({ _id: objectId(studentId), institutionId: tenantId(auth) }); if (!student || (auth.membership.role === "DOCENTE" && !student.courseGroupId)) throw new AppError(404, "NOT_FOUND", "No se encontró el estudiante."); if (student.courseGroupId) assertGroupAccess(auth, String(student.courseGroupId)); } res.json({ items: await listObservations(auth, studentId) }); });
export const observationCreate = run(async (req, res, auth) => { res.status(201).json({ item: await createObservation(auth, observationInput.parse(req.body)) }); });
export const observationUpdateController = run(async (req, res, auth) => { const { id } = idSchema.parse(req.params); const body = z.object({ status: z.enum(["OPEN", "IN_PROGRESS", "CLOSED"]), followUp: z.string().trim().max(2000).optional() }).parse(req.body); const row = await Observation.findOne({ _id: objectId(id), institutionId: tenantId(auth) }); if (!row) throw new AppError(404, "NOT_FOUND", "No se encontró la observación."); const student = await Student.findOne({ _id: row.studentId, institutionId: tenantId(auth) }); if (!student || (auth.membership.role === "DOCENTE" && !student.courseGroupId)) throw new AppError(404, "NOT_FOUND", "No se encontró la observación."); if (student.courseGroupId) assertGroupAccess(auth, String(student.courseGroupId)); const before = { status: row.status, followUp: row.followUp }; row.status = body.status; if (body.followUp !== undefined) row.followUp = body.followUp; await row.save(); await audit(auth, "OBSERVATION_UPDATED", "Observation", row._id, before, { status: row.status, followUp: row.followUp }); res.json({ item: { id: String(row._id), status: row.status, followUp: row.followUp } }); });
export const importPreview = run(async (req, res, auth) => { const kind = z.enum(["students"]).parse(req.params.kind); const file = (req as UploadedRequest).file; if (!file) throw new AppError(400, "FILE_REQUIRED", "Selecciona un archivo para validar."); res.status(201).json(await previewImport(auth, kind, file)); });
export const importRemap = run(async (req, res, auth) => { const { id } = idSchema.parse(req.params); const body = z.object({ mapping: z.record(z.string(), z.string()) }).parse(req.body); res.json(await remapImport(auth, id, body.mapping)); });
export const importConfirm = run(async (req, res, auth) => { const { id } = idSchema.parse(req.params); res.json(await confirmImport(auth, id)); });
export const analyticsRead = run(async (req, res, auth) => { const filters = z.object({ from: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(), to: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(), courseGroupId: idSchema.shape.id.optional(), subjectId: idSchema.shape.id.optional(), periodId: idSchema.shape.id.optional(), studentId: idSchema.shape.id.optional() }).parse(req.query); res.json(await getAnalytics(auth, filters)); });
export const analyticsSettingsGet = run(async (_req, res, auth) => { res.json({ item: await analyticsThresholds(auth) }); });
export const analyticsSettingsPut = run(async (req, res, auth) => { admin(auth); const body = z.object({ attendanceLowPercent: z.number().min(0).max(100), attendanceHighPercent: z.number().min(0).max(100), performanceLowPercent: z.number().min(0).max(100), performanceHighPercent: z.number().min(0).max(100), lateCount: z.number().int().min(1).max(100), consecutiveAbsences: z.number().int().min(1).max(30) }).refine((value) => value.attendanceLowPercent < value.attendanceHighPercent, { message: "El umbral de asistencia baja debe ser menor al de asistencia alta." }).refine((value) => value.performanceLowPercent < value.performanceHighPercent, { message: "El umbral de rendimiento bajo debe ser menor al de rendimiento alto." }).parse(req.body); res.json({ item: await updateAnalyticsThresholds(auth, body) }); });
export const auditList = run(async (_req, res, auth) => { admin(auth); const rows = await AuditLog.find({ institutionId: tenantId(auth) }).sort({ createdAt: -1 }).limit(200).populate("actorUserId", "displayName").lean(); res.json({ items: rows.map((x) => ({ id: String(x._id), actor: (x.actorUserId as unknown as { displayName?: string })?.displayName ?? "Usuario", action: x.action, entityType: x.entityType, entityId: String(x.entityId), before: x.before, after: x.after, at: x.createdAt?.toISOString() })) }); });
export const membershipsList = run(async (_req, res, auth) => { admin(auth); const rows = await Membership.find({ institutionId: tenantId(auth), active: true }).populate("userId", "displayName email").lean(); res.json({ items: rows.map((x) => ({ id: String(x._id), userId: String((x.userId as unknown as { _id: ObjectId })._id), name: (x.userId as unknown as { displayName: string }).displayName, email: (x.userId as unknown as { email?: string }).email, role: x.role, courseGroupIds: x.courseGroupIds.map(String) })) }); });
export const membershipUpdate = run(async (req, res, auth) => { admin(auth); const { id } = idSchema.parse(req.params); const body = z.object({ role: z.enum(["ADMIN", "DOCENTE"]), courseGroupIds: z.array(idSchema.shape.id).max(200) }).parse(req.body); const row = await Membership.findOne({ _id: objectId(id), institutionId: tenantId(auth), active: true }); if (!row) throw new AppError(404, "NOT_FOUND", "No se encontró la membresía."); if (body.role === "DOCENTE" && body.courseGroupIds.length === 0) throw new AppError(400, "GROUP_REQUIRED", "Asigna al menos un grupo al docente."); const groupCount = body.courseGroupIds.length ? await CourseGroup.countDocuments({ _id: { $in: body.courseGroupIds.map((value) => objectId(value)) }, institutionId: tenantId(auth), active: true }) : 0; if (groupCount !== new Set(body.courseGroupIds).size) throw new AppError(400, "GROUP_SCOPE_INVALID", "Uno o más grupos no existen en esta institución."); const isSelf = String(row.userId) === auth.user.id; if (isSelf && body.role !== "ADMIN" && await Membership.countDocuments({ institutionId: tenantId(auth), role: "ADMIN", active: true }) <= 1) throw new AppError(409, "LAST_ADMIN", "No puedes quitar el único acceso administrador activo."); const before = { role: row.role, courseGroupIds: row.courseGroupIds.map(String) }; row.role = body.role; row.courseGroupIds = body.courseGroupIds.map((value) => objectId(value)); await row.save(); await audit(auth, "MEMBERSHIP_UPDATED", "Membership", row._id, before, { role: row.role, courseGroupIds: row.courseGroupIds.map(String) }); res.json({ item: { id: String(row._id), role: row.role, courseGroupIds: row.courseGroupIds.map(String) } }); });
export const membershipRevoke = run(async (req, res, auth) => {
  admin(auth);
  const { id } = idSchema.parse(req.params);
  const row = await Membership.findOne({ _id: objectId(id), institutionId: tenantId(auth), active: true });
  if (!row) throw new AppError(404, "NOT_FOUND", "No se encontró la membresía activa.");
  if (row.userId.equals(actorId(auth))) throw new AppError(409, "SELF_REVOCATION", "No puedes revocar tu propio acceso desde esta pantalla.");
  if (row.role === "ADMIN" && await Membership.countDocuments({ institutionId: tenantId(auth), role: "ADMIN", active: true }) <= 1) throw new AppError(409, "LAST_ADMIN", "No se puede revocar el único acceso administrador activo.");
  const before = { role: row.role, active: row.active, courseGroupIds: row.courseGroupIds.map(String) };
  row.active = false;
  row.courseGroupIds = [];
  await row.save();
  await audit(auth, "MEMBERSHIP_REVOKED", "Membership", row._id, before, { active: false, courseGroupIds: [] });
  res.json({ ok: true });
});
export const invitationsList = run(async (_req, res, auth) => { admin(auth); const rows = await MembershipInvitation.find({ institutionId: tenantId(auth), acceptedAt: { $exists: false }, expiresAt: { $gt: new Date() } }).sort({ createdAt: -1 }).limit(200).lean(); res.json({ items: rows.map((x) => ({ id: String(x._id), email: x.email, role: x.role, courseGroupIds: x.courseGroupIds.map(String), expiresAt: x.expiresAt.toISOString() })) }); });
export const invitationCreate = run(async (req, res, auth) => {
  admin(auth);
  const body = z.object({ email: z.string().trim().email().max(254), role: z.enum(["ADMIN", "DOCENTE"]).default("DOCENTE"), courseGroupIds: z.array(idSchema.shape.id).max(100).default([]) }).parse(req.body);
  const email = body.email.toLowerCase();
  if (body.role === "DOCENTE" && body.courseGroupIds.length === 0) throw new AppError(400, "GROUP_REQUIRED", "Asigna al menos un curso/grupo al docente.");
  const groups = body.courseGroupIds.length ? await CourseGroup.countDocuments({ _id: { $in: body.courseGroupIds.map((id) => objectId(id)) }, institutionId: tenantId(auth), active: true }) : 0;
  if (groups !== new Set(body.courseGroupIds).size) throw new AppError(400, "GROUP_SCOPE_INVALID", "Uno o más grupos no existen o no pertenecen a esta institución.");
  const existing = await User.findOne({ email, active: true });
  if (existing) {
    const prior = await Membership.findOne({ userId: existing._id, institutionId: tenantId(auth) });
    if (prior) throw new AppError(409, "MEMBERSHIP_EXISTS", "La cuenta ya tiene una membresía en esta institución.");
    const membership = await Membership.create({ userId: existing._id, institutionId: tenantId(auth), role: body.role, active: true, courseGroupIds: body.courseGroupIds.map((id) => objectId(id)) });
    await audit(auth, "MEMBERSHIP_CREATED", "Membership", membership._id, undefined, { role: body.role, invitedEmailHash: createHash("sha256").update(email).digest("hex") });
    res.status(201).json({ status: "MEMBER_ADDED", message: "La cuenta ya existía; la membresía quedó activa para su próximo acceso." }); return;
  }
  const duplicate = await MembershipInvitation.findOne({ institutionId: tenantId(auth), email, acceptedAt: { $exists: false }, expiresAt: { $gt: new Date() } });
  if (duplicate) throw new AppError(409, "INVITATION_EXISTS", "Ya existe una invitación vigente para ese correo.");
  const invitation = await MembershipInvitation.create({ institutionId: tenantId(auth), email, role: body.role, courseGroupIds: body.courseGroupIds.map((id) => objectId(id)), invitedBy: actorId(auth), expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000) });
  await audit(auth, "MEMBERSHIP_INVITED", "MembershipInvitation", invitation._id, undefined, { role: body.role, invitedEmailHash: createHash("sha256").update(email).digest("hex"), expiresAt: invitation.expiresAt.toISOString() });
  res.status(201).json({ status: "INVITED", message: `Invitación creada. La persona debe registrarse o iniciar sesión con ${email}; la invitación vence en 30 días.` });
});
export const invitationRevoke = run(async (req, res, auth) => { admin(auth); const { id } = idSchema.parse(req.params); const row = await MembershipInvitation.findOne({ _id: objectId(id), institutionId: tenantId(auth), acceptedAt: { $exists: false } }); if (!row) throw new AppError(404, "NOT_FOUND", "No se encontró una invitación pendiente."); row.expiresAt = new Date(0); await row.save(); await audit(auth, "MEMBERSHIP_INVITATION_REVOKED", "MembershipInvitation", row._id, undefined, { role: row.role }); res.json({ ok: true }); });
export const backupDownload = run(async (_req, res, auth) => {
  admin(auth); const db = mongoose.connection.db; if (!db) throw new AppError(503, "DATABASE_UNAVAILABLE", "MongoDB no está disponible.");
  const names = ["memberships", "membershipinvitations", "coursegroups", "enrollments", "students", "auditlogs", "subjects", "academicperiods", "gradecategories", "assessments", "grades", "schedules", "classsessions", "attendances", "observations", "learningresources", "importjobs"];
  const snapshot: Record<string, unknown[]> = {};
  for (const name of names) {
    const rows = await db.collection(name).find({ institutionId: tenantId(auth) }).limit(20_001).toArray();
    if (rows.length > 20_000) throw new AppError(413, "BACKUP_COLLECTION_LIMIT", `La colección ${name} supera el máximo de 20 000 registros por colección; el respaldo no se truncó.`);
    snapshot[name] = rows;
  }
  snapshot.institutions = await db.collection("institutions").find({ _id: tenantId(auth) }).toArray();
  snapshot.users = await db.collection("users").find({ _id: { $in: (await Membership.find({ institutionId: tenantId(auth) }).select("userId").lean()).map((x) => x.userId) } }).toArray();
  const files = await db.collection("aulanexoResources.files").find({ "metadata.institutionId": auth.institution.id }).limit(501).toArray();
  if (files.length > 500) throw new AppError(413, "BACKUP_FILE_LIMIT", "El respaldo acepta como máximo 500 adjuntos; no se generó un archivo parcial.");
  snapshot.resourceFiles = files;
  let totalBytes = 0; const blobs: { fileId: string; filename: string; contentType: string; dataBase64: string }[] = []; const bucket = new GridFSBucket(db, { bucketName: "aulanexoResources" });
  for (const file of files) { const chunks: Buffer[] = []; await new Promise<void>((resolve, reject) => { const stream = bucket.openDownloadStream(file._id as ObjectId); stream.on("data", (c: Buffer) => { totalBytes += c.length; if (totalBytes > 50 * 1024 * 1024) { stream.destroy(new Error("backup size limit")); return; } chunks.push(c); }); stream.on("error", reject); stream.on("end", resolve); }); blobs.push({ fileId: String(file._id), filename: String(file.filename), contentType: String(file.contentType ?? "application/octet-stream"), dataBase64: Buffer.concat(chunks).toString("base64") }); }
  const { gzipSync } = await import("node:zlib"); const body = gzipSync(Buffer.from(JSON.stringify({ format: "aulanexo-backup-v1", createdAt: new Date().toISOString(), institutionId: auth.institution.id, collections: snapshot, gridfsFiles: blobs }), "utf8"));
  await audit(auth, "INSTITUTION_BACKUP_EXPORTED", "Institution", tenantId(auth), undefined, { collectionCount: Object.keys(snapshot).length, resourceFiles: files.length, compressedBytes: body.length });
  res.setHeader("Content-Type", "application/gzip"); res.setHeader("Content-Disposition", `attachment; filename="aulanexo-backup-${new Date().toISOString().slice(0,10)}.json.gz"`); res.setHeader("Cache-Control", "private, no-store"); res.send(body);
});
