import mongoose, { model, Schema, type Model, type Types } from "mongoose";
import type { MembershipRole } from "../../../shared/types.js";

const schemaOptions = { timestamps: true, versionKey: false as const };

export interface InstitutionRecord { name: string; type: "PERSONAL" | "INSTITUTION"; ownerUserId?: Types.ObjectId; timezone: string; active: boolean; analyticsThresholds?: { attendanceLowPercent: number; attendanceHighPercent: number; performanceLowPercent: number; performanceHighPercent: number; lateCount: number; consecutiveAbsences: number }; createdAt?: Date }
const analyticsThresholdsSchema = new Schema({ attendanceLowPercent: { type: Number, min: 0, max: 100, default: 75 }, attendanceHighPercent: { type: Number, min: 0, max: 100, default: 90 }, performanceLowPercent: { type: Number, min: 0, max: 100, default: 40 }, performanceHighPercent: { type: Number, min: 0, max: 100, default: 80 }, lateCount: { type: Number, min: 1, max: 100, default: 5 }, consecutiveAbsences: { type: Number, min: 1, max: 30, default: 3 } }, { _id: false });
const institutionSchema = new Schema<InstitutionRecord>({ name: { type: String, required: true, trim: true, maxlength: 120 }, type: { type: String, enum: ["PERSONAL", "INSTITUTION"], required: true, default: "PERSONAL", index: true }, ownerUserId: { type: Schema.Types.ObjectId, ref: "User", index: true }, timezone: { type: String, required: true, default: "America/Bogota", maxlength: 64 }, active: { type: Boolean, required: true, default: true }, analyticsThresholds: { type: analyticsThresholdsSchema, default: () => ({}) } }, schemaOptions);
export interface UserRecord { authId: string; displayName: string; email: string; passwordHash: string; active: boolean; lastLoginAt?: Date; lastSeenAt?: Date; createdAt?: Date }
const userSchema = new Schema<UserRecord>({ authId: { type: String, required: true, trim: true, unique: true, index: true }, displayName: { type: String, required: true, trim: true, maxlength: 160 }, email: { type: String, required: true, trim: true, lowercase: true, maxlength: 254, unique: true, index: true }, passwordHash: { type: String, required: true, select: false }, active: { type: Boolean, required: true, default: true }, lastLoginAt: { type: Date }, lastSeenAt: { type: Date } }, schemaOptions);
export interface BootstrapStateRecord { _id: string; userId: Types.ObjectId; institutionId: Types.ObjectId }
const bootstrapStateSchema = new Schema<BootstrapStateRecord>({ _id: { type: String, required: true }, userId: { type: Schema.Types.ObjectId, ref: "User", required: true }, institutionId: { type: Schema.Types.ObjectId, ref: "Institution", required: true } }, { versionKey: false });
export interface MembershipRecord { userId: Types.ObjectId; institutionId: Types.ObjectId; role: MembershipRole; active: boolean; courseGroupIds: Types.ObjectId[] }
const membershipSchema = new Schema<MembershipRecord>({ userId: { type: Schema.Types.ObjectId, ref: "User", required: true, index: true }, institutionId: { type: Schema.Types.ObjectId, ref: "Institution", required: true, index: true }, role: { type: String, required: true, enum: ["ADMIN", "DOCENTE"] }, active: { type: Boolean, required: true, default: true }, courseGroupIds: [{ type: Schema.Types.ObjectId, ref: "CourseGroup" }] }, schemaOptions);
membershipSchema.index({ userId: 1, institutionId: 1 }, { unique: true });
export interface MembershipInvitationRecord { institutionId: Types.ObjectId; email: string; role: MembershipRole; courseGroupIds: Types.ObjectId[]; invitedBy: Types.ObjectId; expiresAt: Date; acceptedAt?: Date; acceptedBy?: Types.ObjectId }
const membershipInvitationSchema = new Schema<MembershipInvitationRecord>({ institutionId: { type: Schema.Types.ObjectId, ref: "Institution", required: true, index: true }, email: { type: String, required: true, trim: true, lowercase: true, maxlength: 254, index: true }, role: { type: String, required: true, enum: ["ADMIN", "DOCENTE"] }, courseGroupIds: [{ type: Schema.Types.ObjectId, ref: "CourseGroup" }], invitedBy: { type: Schema.Types.ObjectId, ref: "User", required: true }, expiresAt: { type: Date, required: true, index: true }, acceptedAt: { type: Date }, acceptedBy: { type: Schema.Types.ObjectId, ref: "User" } }, schemaOptions);
membershipInvitationSchema.index({ institutionId: 1, email: 1, acceptedAt: 1, expiresAt: 1 });
export interface CourseGroupRecord { institutionId: Types.ObjectId; grade: string; gradeNormalized: string; group: string; groupNormalized: string; academicYear: number; active: boolean }
const courseGroupSchema = new Schema<CourseGroupRecord>({ institutionId: { type: Schema.Types.ObjectId, ref: "Institution", required: true, index: true }, grade: { type: String, required: true, trim: true, maxlength: 64 }, gradeNormalized: { type: String, required: true, trim: true, maxlength: 64 }, group: { type: String, required: true, trim: true, maxlength: 32 }, groupNormalized: { type: String, required: true, trim: true, maxlength: 32 }, academicYear: { type: Number, required: true, min: 2000, max: 2200 }, active: { type: Boolean, required: true, default: true } }, schemaOptions);
courseGroupSchema.index({ institutionId: 1, gradeNormalized: 1, groupNormalized: 1, academicYear: 1 }, { unique: true });
export interface EnrollmentRecord { institutionId: Types.ObjectId; studentId: Types.ObjectId; courseGroupId: Types.ObjectId; startsOn: Date; endsOn?: Date; active: boolean }
const enrollmentSchema = new Schema<EnrollmentRecord>({ institutionId: { type: Schema.Types.ObjectId, ref: "Institution", required: true, index: true }, studentId: { type: Schema.Types.ObjectId, ref: "Student", required: true, index: true }, courseGroupId: { type: Schema.Types.ObjectId, ref: "CourseGroup", required: true, index: true }, startsOn: { type: Date, required: true }, endsOn: { type: Date }, active: { type: Boolean, required: true, default: true } }, schemaOptions);
enrollmentSchema.index({ institutionId: 1, studentId: 1, active: 1 });
export interface StudentRecord { institutionId: Types.ObjectId; firstName: string; lastName: string; document: string; documentNormalized: string; courseGroupId?: Types.ObjectId; email?: string; phone?: string; active: boolean; qrTokenHash: string; qrVersion: number; createdBy: Types.ObjectId }
const studentSchema = new Schema<StudentRecord>({ institutionId: { type: Schema.Types.ObjectId, ref: "Institution", required: true, index: true }, firstName: { type: String, required: true, trim: true, maxlength: 80 }, lastName: { type: String, required: true, trim: true, maxlength: 100 }, document: { type: String, required: true, trim: true, maxlength: 64 }, documentNormalized: { type: String, required: true, trim: true, maxlength: 64 }, courseGroupId: { type: Schema.Types.ObjectId, ref: "CourseGroup" }, email: { type: String, trim: true, lowercase: true, maxlength: 254 }, phone: { type: String, trim: true, maxlength: 32 }, active: { type: Boolean, required: true, default: true }, qrTokenHash: { type: String, required: true, trim: true, maxlength: 128 }, qrVersion: { type: Number, required: true, min: 1, default: 1 }, createdBy: { type: Schema.Types.ObjectId, ref: "User", required: true } }, schemaOptions);
studentSchema.index({ institutionId: 1, documentNormalized: 1 }, { unique: true });
studentSchema.index({ institutionId: 1, qrTokenHash: 1 }, { unique: true });
studentSchema.index({ institutionId: 1, active: 1, lastName: 1, firstName: 1 });
// Consulta pública del estudiante por código o QR (sin saber su aula).
studentSchema.index({ documentNormalized: 1 });
studentSchema.index({ qrTokenHash: 1 });
export interface AuditLogRecord { institutionId: Types.ObjectId; actorUserId: Types.ObjectId; action: string; entityType: string; entityId: Types.ObjectId; before?: Record<string, unknown>; after?: Record<string, unknown>; metadata?: Record<string, unknown>; createdAt?: Date; updatedAt?: Date }
const auditLogSchema = new Schema<AuditLogRecord>({ institutionId: { type: Schema.Types.ObjectId, ref: "Institution", required: true, index: true }, actorUserId: { type: Schema.Types.ObjectId, ref: "User", required: true, index: true }, action: { type: String, required: true, trim: true, maxlength: 100 }, entityType: { type: String, required: true, trim: true, maxlength: 80 }, entityId: { type: Schema.Types.ObjectId, required: true, index: true }, before: { type: Schema.Types.Mixed }, after: { type: Schema.Types.Mixed }, metadata: { type: Schema.Types.Mixed } }, schemaOptions);
auditLogSchema.index({ institutionId: 1, entityType: 1, entityId: 1, createdAt: -1 });
export const Institution: Model<InstitutionRecord> = (mongoose.models.Institution as Model<InstitutionRecord> | undefined) ?? model<InstitutionRecord>("Institution", institutionSchema);
export const User: Model<UserRecord> = (mongoose.models.User as Model<UserRecord> | undefined) ?? model<UserRecord>("User", userSchema);
export const BootstrapState: Model<BootstrapStateRecord> = (mongoose.models.BootstrapState as Model<BootstrapStateRecord> | undefined) ?? model<BootstrapStateRecord>("BootstrapState", bootstrapStateSchema);
export const Membership: Model<MembershipRecord> = (mongoose.models.Membership as Model<MembershipRecord> | undefined) ?? model<MembershipRecord>("Membership", membershipSchema);
export const MembershipInvitation: Model<MembershipInvitationRecord> = (mongoose.models.MembershipInvitation as Model<MembershipInvitationRecord> | undefined) ?? model<MembershipInvitationRecord>("MembershipInvitation", membershipInvitationSchema);
export const CourseGroup: Model<CourseGroupRecord> = (mongoose.models.CourseGroup as Model<CourseGroupRecord> | undefined) ?? model<CourseGroupRecord>("CourseGroup", courseGroupSchema);
export const Enrollment: Model<EnrollmentRecord> = (mongoose.models.Enrollment as Model<EnrollmentRecord> | undefined) ?? model<EnrollmentRecord>("Enrollment", enrollmentSchema);
export const Student: Model<StudentRecord> = (mongoose.models.Student as Model<StudentRecord> | undefined) ?? model<StudentRecord>("Student", studentSchema);
export const AuditLog: Model<AuditLogRecord> = (mongoose.models.AuditLog as Model<AuditLogRecord> | undefined) ?? model<AuditLogRecord>("AuditLog", auditLogSchema);
